.EQ
-2 a + -2 b !=  y +  x
.EN

.EQ
20 a sup 2 + 2 a !=  a +  b + 3
.EN

.EQ
 x sup 3 + 3 x sup 2 y + 3 y sup 2 x +  y sup 3 =  x sup 3 + 3 x sup 2 y + 3 y sup 2 x +  y sup 3
.EN

.EQ
 y sup 2 +  x z + 2 x sup 2 +  y z + 3 y x =  y sup 2 +  x z + 2 x sup 2 +  y z + 3 y x
.EN

.EQ
 x sup 2 y + 8 x + 8 y x + 3 y sup 2 x =  x sup 2 y + 8 x + 8 y x + 3 y sup 2 x
.EN

.EQ
 x sup 2 + 2 y x +  y sup 2 =  x sup 2 + 2 y x +  y sup 2
.EN

